### ISSUE TITLE
Inserimento navi a partire da un'origine

### ISSUE THREAD

**Issue by supix** [Simonecalzavara/Battaglia_Navale#3]
La soluzione progettata consente ad un utente di _sparpagliare_ le celle di una nave per il campo di gioco, senza controllare che il giocatore piazzi le celle tutte in modo contiguo e nella medesima direzione.

Inoltre due navi potrebbero anche risultare sovrapposte.

Potrebbe essere più corretto (e semplice) consentire al giocatore di specificare solo la cella _iniziale_ della nave e la sua direzione. Si occuperebbe poi il programma stesso di riempire le celle.

Il programma deve inoltre assicurare che una nave non possa essere piazzata (anche solo parzialmente) fuori dal campo di gioco.

**Comment by Simonecalzavara** [comment]
Ho aggiornato la classe navi, inserendo dei controlli sull'inserimento delle navi. Ora le navi vengono posizionate in maniera contigua secondo una direzione ed in due possibili gonfigurazioni, verticale od orizzontale.
Inoltre le navi vengono inserite in maniera automatica.

**Comment by supix** [comment]
L'esecuzione dà il seguente errore.

```
Traceback (most recent call last):
  File "c:\Battaglia_Navale\main.py", line 35, in <module>
    b.board_add(ship,legenda_asse_orizzontale_iniziale,board,row_size,col_size)
TypeError: board_add() takes 4 positional arguments but 5 were given
```
