### ISSUE TITLE
Mancato controllo input d'utente

### ISSUE THREAD

**Issue by supix** [Simonecalzavara/Battaglia_Navale#4]
Il programma va in crash se si inserisce una coordinata formalmente invalida (per es. `A`).

**Comment by Simonecalzavara** [comment]
è stata estesa la logica di controllo dell'inserimento delle coordinate

**Comment by supix** [comment]
Bene la possibilità di inserire `2A` o `A2` indifferentemente. L'applicativo consente però anche la specifica della coordinata formalmente invalida `A2B` interpretandola come `A2`.

**Comment by Simonecalzavara** [comment]
L'applicativo ora non permette l'inserimento di una coordinata non valida contenente piú di una coordinata per colonna
