### ISSUE TITLE
Errore nell'algoritmo di verifica delle collisioni.

### ISSUE THREAD

**Issue by supix** [Simonecalzavara/Battaglia_Navale#5]
Se inserisco una nave verticale in I7 di 3 caselle non mi fa inserire una nave orizzontale in A9 di 3 caselle per il falso rilevamento di una collisione.

**Comment by Simonecalzavara** [comment]
Il rilevamento delle false collisioni é stato risolto andando ad aggiungere ulteriori controlli quando le navi vengono piazzate agli estremi del tavolo da gioco.
