### ISSUE TITLE
Miglioramento grafico: evidenza nave affondata

### ISSUE THREAD

**Issue by supix** [Simonecalzavara/Battaglia_Navale#6]
Dall'interfaccia grafica non si ha percezione di quando una nave è stata affondata (il che facilita il giocatore a concentrarsi sul resto del campo da gioco).

**Comment by Simonecalzavara** [comment]
E' stato implementato un sistema di colori all'interno del gioco. Quando il colpo viene mancato verrá visualizzato come rosso, un colpo andato a buon fine sará giallo mentre una nave affondata verrá visualizzata come verde
