### ISSUE TITLE
Modalità di alternanza dei turni di gioco

### ISSUE THREAD

**Issue by supix** [Simonecalzavara/Battaglia_Navale#7]
Non è disponibile la doppia modalità di alternanza dei turni di gioco indicata nelle specifiche.

**Comment by Simonecalzavara** [comment]
La doppia modalità è disponibile andando a variare l’opzione durante l’avvio da terminale. 
Avviando il gioco utilizzando python main.py -o 1 viene impostata la modalità alternata dei turni, altrimenti di default il turno non finisce fino a quando non viene sbagliato un colpo dai giocatori

**Comment by iannellog** [comment]
Bisognerebbe aggiornare il README per spiegare l'introduzione di questa nuova opzione.

**Comment by Simonecalzavara** [comment]
Ora all'interno del Readme é presente una sezione dove é possibile visualizzare tutti i parametri che possonoe essere configurati durante l'inizializzazione della partita , compresa la modalita di gioco
