### ISSUE TITLE
Commenti nel file game.py

### ISSUE THREAD

**Issue by iannellog** [Simonecalzavara/Battaglia_Navale#8]
Anche se i parametri delle funzioni sono documentati, mancano i commenti che spiegano sinteticamente cosa fanno le funzioni. 
Questo costringe a leggere tutto il codice per comprendere.
Sempre per facilitare la lettura del codice ci vorrebbe qualche commento in più che spieghi il senso di alcune frasi. 
Per esempio alle righe 89 e 107 la frase:

> if not ship.coordinate:

che cosa verifica? ship.coordinate è una lista e sembra venga interpretata come valore logico, ma per indicare cosa?

**Comment by Simonecalzavara** [comment]
Provvedo ad aggiungere dei commenti più dettagliati al codice. Nello specifico la condizione : ``not ship.coordinate`` verifica se la lista delle coordinate sia vuota. Nel caso in cui sia vuota si provvede ad eliminare la specifica nave dalla lista delle navi del giocatore.

**Comment by Simonecalzavara** [comment]
Sono stati aggiunti dei commenti relativi a porzioni del codice per facilitarne la lettura
